package model;
// Generated 01-Apr-2018 15:38:20 by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private String user;
     private String pass;
     private Integer idGroup;

    public Login() {
    }

	
    public Login(String user, String pass) {
        this.user = user;
        this.pass = pass;
    }
    public Login(String user, String pass, Integer idGroup) {
       this.user = user;
       this.pass = pass;
       this.idGroup = idGroup;
    }
   
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Integer getIdGroup() {
        return this.idGroup;
    }
    
    public void setIdGroup(Integer idGroup) {
        this.idGroup = idGroup;
    }




}


