package model;
// Generated 01-Apr-2018 15:38:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Phieurut generated by hbm2java
 */
public class Phieurut  implements java.io.Serializable {


     private String idphieuRut;
     private String idsoTk;
     private float soTienRut;
     private Date ngayRut;
     private String nguoiRut;

    public Phieurut() {
    }

    public Phieurut(String idphieuRut, String idsoTk, float soTienRut, Date ngayRut, String nguoiRut) {
       this.idphieuRut = idphieuRut;
       this.idsoTk = idsoTk;
       this.soTienRut = soTienRut;
       this.ngayRut = ngayRut;
       this.nguoiRut = nguoiRut;
    }
   
    public String getIdphieuRut() {
        return this.idphieuRut;
    }
    
    public void setIdphieuRut(String idphieuRut) {
        this.idphieuRut = idphieuRut;
    }
    public String getIdsoTk() {
        return this.idsoTk;
    }
    
    public void setIdsoTk(String idsoTk) {
        this.idsoTk = idsoTk;
    }
    public float getSoTienRut() {
        return this.soTienRut;
    }
    
    public void setSoTienRut(float soTienRut) {
        this.soTienRut = soTienRut;
    }
    public Date getNgayRut() {
        return this.ngayRut;
    }
    
    public void setNgayRut(Date ngayRut) {
        this.ngayRut = ngayRut;
    }
    public String getNguoiRut() {
        return this.nguoiRut;
    }
    
    public void setNguoiRut(String nguoiRut) {
        this.nguoiRut = nguoiRut;
    }




}


