package model;
// Generated 01-Apr-2018 15:38:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sotietkiem generated by hbm2java
 */
public class Sotietkiem  implements java.io.Serializable {


     private String idstk;
     private float soTienGuiTk;
     private Date ngayMo;
     private boolean dongSo;
     private String idkh;
     private String idloaiTien;
     private int idloaiTietKiem;
     private Date ngayTinhLai;
     private Date ngayDenHan;
     private float tongTien;
     private boolean isActive;

    public Sotietkiem() {
    }

	
    public Sotietkiem(String idstk, float soTienGuiTk, Date ngayMo, boolean dongSo, String idkh, String idloaiTien, int idloaiTietKiem, float tongTien, boolean isActive) {
        this.idstk = idstk;
        this.soTienGuiTk = soTienGuiTk;
        this.ngayMo = ngayMo;
        this.dongSo = dongSo;
        this.idkh = idkh;
        this.idloaiTien = idloaiTien;
        this.idloaiTietKiem = idloaiTietKiem;
        this.tongTien = tongTien;
        this.isActive = isActive;
    }
    public Sotietkiem(String idstk, float soTienGuiTk, Date ngayMo, boolean dongSo, String idkh, String idloaiTien, int idloaiTietKiem, Date ngayTinhLai, Date ngayDenHan, float tongTien, boolean isActive) {
       this.idstk = idstk;
       this.soTienGuiTk = soTienGuiTk;
       this.ngayMo = ngayMo;
       this.dongSo = dongSo;
       this.idkh = idkh;
       this.idloaiTien = idloaiTien;
       this.idloaiTietKiem = idloaiTietKiem;
       this.ngayTinhLai = ngayTinhLai;
       this.ngayDenHan = ngayDenHan;
       this.tongTien = tongTien;
       this.isActive = isActive;
    }
   
    public String getIdstk() {
        return this.idstk;
    }
    
    public void setIdstk(String idstk) {
        this.idstk = idstk;
    }
    public float getSoTienGuiTk() {
        return this.soTienGuiTk;
    }
    
    public void setSoTienGuiTk(float soTienGuiTk) {
        this.soTienGuiTk = soTienGuiTk;
    }
    public Date getNgayMo() {
        return this.ngayMo;
    }
    
    public void setNgayMo(Date ngayMo) {
        this.ngayMo = ngayMo;
    }
    public boolean isDongSo() {
        return this.dongSo;
    }
    
    public void setDongSo(boolean dongSo) {
        this.dongSo = dongSo;
    }
    public String getIdkh() {
        return this.idkh;
    }
    
    public void setIdkh(String idkh) {
        this.idkh = idkh;
    }
    public String getIdloaiTien() {
        return this.idloaiTien;
    }
    
    public void setIdloaiTien(String idloaiTien) {
        this.idloaiTien = idloaiTien;
    }
    public int getIdloaiTietKiem() {
        return this.idloaiTietKiem;
    }
    
    public void setIdloaiTietKiem(int idloaiTietKiem) {
        this.idloaiTietKiem = idloaiTietKiem;
    }
    public Date getNgayTinhLai() {
        return this.ngayTinhLai;
    }
    
    public void setNgayTinhLai(Date ngayTinhLai) {
        this.ngayTinhLai = ngayTinhLai;
    }
    public Date getNgayDenHan() {
        return this.ngayDenHan;
    }
    
    public void setNgayDenHan(Date ngayDenHan) {
        this.ngayDenHan = ngayDenHan;
    }
    public float getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(float tongTien) {
        this.tongTien = tongTien;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


