package model;
// Generated 01-Apr-2018 15:38:20 by Hibernate Tools 4.3.1



/**
 * Thamso generated by hbm2java
 */
public class Thamso  implements java.io.Serializable {


     private int idquyDinhSoTien;
     private String tenQuyDinh;
     private float soTienGuiToiThieu;
     private float soTienGuiToiDa;
     private float soTienGuiThemToiThieu;

    public Thamso() {
    }

	
    public Thamso(int idquyDinhSoTien, float soTienGuiToiThieu, float soTienGuiToiDa, float soTienGuiThemToiThieu) {
        this.idquyDinhSoTien = idquyDinhSoTien;
        this.soTienGuiToiThieu = soTienGuiToiThieu;
        this.soTienGuiToiDa = soTienGuiToiDa;
        this.soTienGuiThemToiThieu = soTienGuiThemToiThieu;
    }
    public Thamso(int idquyDinhSoTien, String tenQuyDinh, float soTienGuiToiThieu, float soTienGuiToiDa, float soTienGuiThemToiThieu) {
       this.idquyDinhSoTien = idquyDinhSoTien;
       this.tenQuyDinh = tenQuyDinh;
       this.soTienGuiToiThieu = soTienGuiToiThieu;
       this.soTienGuiToiDa = soTienGuiToiDa;
       this.soTienGuiThemToiThieu = soTienGuiThemToiThieu;
    }
   
    public int getIdquyDinhSoTien() {
        return this.idquyDinhSoTien;
    }
    
    public void setIdquyDinhSoTien(int idquyDinhSoTien) {
        this.idquyDinhSoTien = idquyDinhSoTien;
    }
    public String getTenQuyDinh() {
        return this.tenQuyDinh;
    }
    
    public void setTenQuyDinh(String tenQuyDinh) {
        this.tenQuyDinh = tenQuyDinh;
    }
    public float getSoTienGuiToiThieu() {
        return this.soTienGuiToiThieu;
    }
    
    public void setSoTienGuiToiThieu(float soTienGuiToiThieu) {
        this.soTienGuiToiThieu = soTienGuiToiThieu;
    }
    public float getSoTienGuiToiDa() {
        return this.soTienGuiToiDa;
    }
    
    public void setSoTienGuiToiDa(float soTienGuiToiDa) {
        this.soTienGuiToiDa = soTienGuiToiDa;
    }
    public float getSoTienGuiThemToiThieu() {
        return this.soTienGuiThemToiThieu;
    }
    
    public void setSoTienGuiThemToiThieu(float soTienGuiThemToiThieu) {
        this.soTienGuiThemToiThieu = soTienGuiThemToiThieu;
    }




}


