package model;
// Generated 01-Apr-2018 15:38:20 by Hibernate Tools 4.3.1



/**
 * Tinhlai generated by hbm2java
 */
public class Tinhlai  implements java.io.Serializable {


     private int idTinhlai;
     private String idstk;
     private String soTienGoc;
     private String tongLaiSuat;

    public Tinhlai() {
    }

    public Tinhlai(int idTinhlai, String idstk, String soTienGoc, String tongLaiSuat) {
       this.idTinhlai = idTinhlai;
       this.idstk = idstk;
       this.soTienGoc = soTienGoc;
       this.tongLaiSuat = tongLaiSuat;
    }
   
    public int getIdTinhlai() {
        return this.idTinhlai;
    }
    
    public void setIdTinhlai(int idTinhlai) {
        this.idTinhlai = idTinhlai;
    }
    public String getIdstk() {
        return this.idstk;
    }
    
    public void setIdstk(String idstk) {
        this.idstk = idstk;
    }
    public String getSoTienGoc() {
        return this.soTienGoc;
    }
    
    public void setSoTienGoc(String soTienGoc) {
        this.soTienGoc = soTienGoc;
    }
    public String getTongLaiSuat() {
        return this.tongLaiSuat;
    }
    
    public void setTongLaiSuat(String tongLaiSuat) {
        this.tongLaiSuat = tongLaiSuat;
    }




}


